package dhcp

// OptionDef describes a DHCP option from IANA registry
type OptionDef struct {
	Code        byte
	Name        string
	Length      string
	Description string
	Type        string
}

// OptionRegistry maps DHCP option code to its IANA definition.
var OptionRegistry = map[byte]OptionDef{
	0:   {Code: 0, Name: "Pad", Length: "0", Description: "None", Type: "none"},
	1:   {Code: 1, Name: "Subnet Mask", Length: "4", Description: "Subnet Mask Value", Type: "ip"},
	2:   {Code: 2, Name: "Time Offset", Length: "4", Description: "Time Offset in Seconds from UTC                    (note: deprecated by 100 and 101)", Type: "int32"},
	3:   {Code: 3, Name: "Router", Length: "N", Description: "N/4 Router addresses", Type: "ips"},
	4:   {Code: 4, Name: "Time Server", Length: "N", Description: "N/4 Timeserver addresses", Type: "ips"},
	5:   {Code: 5, Name: "Name Server", Length: "N", Description: "N/4 IEN-116 Server addresses", Type: "ips"},
	6:   {Code: 6, Name: "Domain Server", Length: "N", Description: "N/4 DNS Server addresses", Type: "ips"},
	7:   {Code: 7, Name: "Log Server", Length: "N", Description: "N/4 Logging Server addresses", Type: "ips"},
	8:   {Code: 8, Name: "Quotes Server", Length: "N", Description: "N/4 Quotes Server addresses", Type: "ips"},
	9:   {Code: 9, Name: "LPR Server", Length: "N", Description: "N/4 Printer Server addresses", Type: "ips"},
	10:  {Code: 10, Name: "Impress Server", Length: "N", Description: "N/4 Impress Server addresses", Type: "ips"},
	11:  {Code: 11, Name: "RLP Server", Length: "N", Description: "N/4 RLP Server addresses", Type: "ips"},
	12:  {Code: 12, Name: "Hostname", Length: "N", Description: "Hostname string", Type: "string"},
	13:  {Code: 13, Name: "Boot File Size", Length: "2", Description: "Size of boot file in 512 byte chunks", Type: "uint16"},
	14:  {Code: 14, Name: "Merit Dump File", Length: "N", Description: "Client to dump and name the file to dump it to", Type: "string"},
	15:  {Code: 15, Name: "Domain Name", Length: "N", Description: "The DNS domain name of the client", Type: "string"},
	16:  {Code: 16, Name: "Swap Server", Length: "N", Description: "Swap Server address", Type: "ip"},
	17:  {Code: 17, Name: "Root Path", Length: "N", Description: "Path name for root disk", Type: "string"},
	18:  {Code: 18, Name: "Extension File", Length: "N", Description: "Path name for more BOOTP info", Type: "string"},
	19:  {Code: 19, Name: "Forward On/Off", Length: "1", Description: "Enable/Disable IP Forwarding", Type: "uint8"},
	20:  {Code: 20, Name: "SrcRte On/Off", Length: "1", Description: "Enable/Disable Source Routing", Type: "uint8"},
	21:  {Code: 21, Name: "Policy Filter", Length: "N", Description: "Routing Policy Filters", Type: "hex"},
	22:  {Code: 22, Name: "Max DG Assembly", Length: "2", Description: "Max Datagram Reassembly Size", Type: "uint16"},
	23:  {Code: 23, Name: "Default IP TTL", Length: "1", Description: "Default IP Time to Live", Type: "uint8"},
	24:  {Code: 24, Name: "MTU Timeout", Length: "4", Description: "Path MTU Aging Timeout", Type: "uint32"},
	25:  {Code: 25, Name: "MTU Plateau", Length: "N", Description: "Path MTU  Plateau Table", Type: "hex"},
	26:  {Code: 26, Name: "MTU Interface", Length: "2", Description: "Interface MTU Size", Type: "uint16"},
	27:  {Code: 27, Name: "MTU Subnet", Length: "1", Description: "All Subnets are Local", Type: "uint8"},
	28:  {Code: 28, Name: "Broadcast Address", Length: "4", Description: "Broadcast Address", Type: "ip"},
	29:  {Code: 29, Name: "Mask Discovery", Length: "1", Description: "Perform Mask Discovery", Type: "uint8"},
	30:  {Code: 30, Name: "Mask Supplier", Length: "1", Description: "Provide Mask to Others", Type: "uint8"},
	31:  {Code: 31, Name: "Router Discovery", Length: "1", Description: "Perform Router Discovery", Type: "uint8"},
	32:  {Code: 32, Name: "Router Request", Length: "4", Description: "Router Solicitation Address", Type: "ip"},
	33:  {Code: 33, Name: "Static Route", Length: "N", Description: "Static Routing Table", Type: "routes"},
	34:  {Code: 34, Name: "Trailers", Length: "1", Description: "Trailer Encapsulation", Type: "uint8"},
	35:  {Code: 35, Name: "ARP Timeout", Length: "4", Description: "ARP Cache Timeout", Type: "uint32"},
	36:  {Code: 36, Name: "Ethernet", Length: "1", Description: "Ethernet Encapsulation", Type: "uint8"},
	37:  {Code: 37, Name: "Default TCP TTL", Length: "1", Description: "Default TCP Time to Live", Type: "uint8"},
	38:  {Code: 38, Name: "Keepalive Time", Length: "4", Description: "TCP Keepalive Interval", Type: "uint32"},
	39:  {Code: 39, Name: "Keepalive Data", Length: "1", Description: "TCP Keepalive Garbage", Type: "uint8"},
	40:  {Code: 40, Name: "NIS Domain", Length: "N", Description: "NIS Domain Name", Type: "string"},
	41:  {Code: 41, Name: "NIS Servers", Length: "N", Description: "NIS Server Addresses", Type: "ips"},
	42:  {Code: 42, Name: "NTP Servers", Length: "N", Description: "NTP Server Addresses", Type: "ips"},
	43:  {Code: 43, Name: "Vendor Specific", Length: "N", Description: "Vendor Specific Information", Type: "hex"},
	44:  {Code: 44, Name: "NETBIOS Name Srv", Length: "N", Description: "NETBIOS Name Servers", Type: "ips"},
	45:  {Code: 45, Name: "NETBIOS Dist Srv", Length: "N", Description: "NETBIOS Datagram Distribution", Type: "ips"},
	46:  {Code: 46, Name: "NETBIOS Node Type", Length: "1", Description: "NETBIOS Node Type", Type: "uint8"},
	47:  {Code: 47, Name: "NETBIOS Scope", Length: "N", Description: "NETBIOS Scope", Type: "hex"},
	48:  {Code: 48, Name: "X Window Font", Length: "N", Description: "X Window Font Server", Type: "ips"},
	49:  {Code: 49, Name: "X Window Manager", Length: "N", Description: "X Window Display Manager", Type: "ips"},
	50:  {Code: 50, Name: "Address Request", Length: "4", Description: "Requested IP Address", Type: "ip"},
	51:  {Code: 51, Name: "Address Time", Length: "4", Description: "IP Address Lease Time", Type: "uint32"},
	52:  {Code: 52, Name: "Overload", Length: "1", Description: "Overload \"sname\" or \"file\"", Type: "uint8"},
	53:  {Code: 53, Name: "DHCP Msg Type", Length: "1", Description: "DHCP Message Type", Type: "uint8"},
	54:  {Code: 54, Name: "DHCP Server Id", Length: "4", Description: "DHCP Server Identification", Type: "ip"},
	55:  {Code: 55, Name: "Parameter List", Length: "N", Description: "Parameter Request List", Type: "hex"},
	56:  {Code: 56, Name: "DHCP Message", Length: "N", Description: "DHCP Error Message", Type: "string"},
	57:  {Code: 57, Name: "DHCP Max Msg Size", Length: "2", Description: "DHCP Maximum Message Size", Type: "uint16"},
	58:  {Code: 58, Name: "Renewal Time", Length: "4", Description: "DHCP Renewal (T1) Time", Type: "uint32"},
	59:  {Code: 59, Name: "Rebinding Time", Length: "4", Description: "DHCP Rebinding (T2) Time", Type: "uint32"},
	60:  {Code: 60, Name: "Class Id", Length: "N", Description: "Class Identifier", Type: "string"},
	61:  {Code: 61, Name: "Client Id", Length: "N", Description: "Client Identifier", Type: "hex"},
	62:  {Code: 62, Name: "NetWare/IP Domain", Length: "N", Description: "NetWare/IP Domain Name", Type: "string"},
	63:  {Code: 63, Name: "NetWare/IP Option", Length: "N", Description: "NetWare/IP sub Options", Type: "hex"},
	64:  {Code: 64, Name: "NIS-Domain-Name", Length: "N", Description: "NIS+ v3 Client Domain Name", Type: "string"},
	65:  {Code: 65, Name: "NIS-Server-Addr", Length: "N", Description: "NIS+ v3 Server Addresses", Type: "ips"},
	66:  {Code: 66, Name: "Server-Name", Length: "N", Description: "TFTP Server Name", Type: "string"},
	67:  {Code: 67, Name: "Bootfile-Name", Length: "N", Description: "Boot File Name", Type: "string"},
	68:  {Code: 68, Name: "Home-Agent-Addrs", Length: "N", Description: "Home Agent Addresses", Type: "ips"},
	69:  {Code: 69, Name: "SMTP-Server", Length: "N", Description: "Simple Mail Server Addresses", Type: "ips"},
	70:  {Code: 70, Name: "POP3-Server", Length: "N", Description: "Post Office Server Addresses", Type: "ips"},
	71:  {Code: 71, Name: "NNTP-Server", Length: "N", Description: "Network News Server Addresses", Type: "ips"},
	72:  {Code: 72, Name: "WWW-Server", Length: "N", Description: "WWW Server Addresses", Type: "ips"},
	73:  {Code: 73, Name: "Finger-Server", Length: "N", Description: "Finger Server Addresses", Type: "ips"},
	74:  {Code: 74, Name: "IRC-Server", Length: "N", Description: "Chat Server Addresses", Type: "ips"},
	75:  {Code: 75, Name: "StreetTalk-Server", Length: "N", Description: "StreetTalk Server Addresses", Type: "ips"},
	76:  {Code: 76, Name: "STDA-Server", Length: "N", Description: "ST Directory Assist. Addresses", Type: "ips"},
	77:  {Code: 77, Name: "User-Class", Length: "N", Description: "User Class Information", Type: "string"},
	78:  {Code: 78, Name: "Directory Agent", Length: "N", Description: "directory agent information", Type: "hex"},
	79:  {Code: 79, Name: "Service Scope", Length: "N", Description: "service location agent scope", Type: "hex"},
	80:  {Code: 80, Name: "Rapid Commit", Length: "0", Description: "Rapid Commit", Type: "hex"},
	81:  {Code: 81, Name: "Client FQDN", Length: "N", Description: "Fully Qualified Domain Name", Type: "hex"},
	82:  {Code: 82, Name: "Relay Agent Information", Length: "N", Description: "Relay Agent Information", Type: "hex"},
	83:  {Code: 83, Name: "iSNS", Length: "N", Description: "Internet Storage Name Service", Type: "string"},
	84:  {Code: 84, Name: "REMOVED/Unassigned", Length: "", Description: "", Type: "hex"},
	85:  {Code: 85, Name: "NDS Servers", Length: "N", Description: "Novell Directory Services", Type: "ips"},
	86:  {Code: 86, Name: "NDS Tree Name", Length: "N", Description: "Novell Directory Services", Type: "string"},
	87:  {Code: 87, Name: "NDS Context", Length: "N", Description: "Novell Directory Services", Type: "hex"},
	88:  {Code: 88, Name: "BCMCS Controller Domain Name list", Length: "", Description: "", Type: "hex"},
	89:  {Code: 89, Name: "BCMCS Controller IPv4 address option", Length: "", Description: "", Type: "hex"},
	90:  {Code: 90, Name: "Authentication", Length: "N", Description: "Authentication", Type: "hex"},
	91:  {Code: 91, Name: "client-last-transaction-time option", Length: "", Description: "", Type: "hex"},
	92:  {Code: 92, Name: "associated-ip option", Length: "", Description: "", Type: "hex"},
	93:  {Code: 93, Name: "Client System", Length: "N", Description: "Client System Architecture", Type: "hex"},
	94:  {Code: 94, Name: "Client NDI", Length: "N", Description: "Client Network Device Interface", Type: "hex"},
	95:  {Code: 95, Name: "LDAP", Length: "N", Description: "Lightweight Directory Access Protocol", Type: "hex"},
	96:  {Code: 96, Name: "REMOVED/Unassigned", Length: "", Description: "", Type: "hex"},
	97:  {Code: 97, Name: "UUID/GUID", Length: "N", Description: "UUID/GUID-based Client Identifier", Type: "hex"},
	98:  {Code: 98, Name: "User-Auth", Length: "N", Description: "Open Group's User Authentication", Type: "hex"},
	99:  {Code: 99, Name: "GEOCONF_CIVIC", Length: "", Description: "", Type: "hex"},
	100: {Code: 100, Name: "PCode", Length: "N", Description: "IEEE 1003.1 TZ String", Type: "string"},
	101: {Code: 101, Name: "TCode", Length: "N", Description: "Reference to the TZ Database", Type: "string"},
	108: {Code: 108, Name: "IPv6-Only Preferred", Length: "4", Description: "Number of seconds that DHCPv4 should be disabled", Type: "ip"},
	109: {Code: 109, Name: "OPTION_DHCP4O6_S46_SADDR", Length: "16", Description: "DHCPv4 over DHCPv6 Softwire Source Address Option", Type: "hex"},
	110: {Code: 110, Name: "REMOVED/Unassigned", Length: "", Description: "", Type: "hex"},
	111: {Code: 111, Name: "Unassigned", Length: "", Description: "", Type: "hex"},
	112: {Code: 112, Name: "Netinfo Address", Length: "N", Description: "NetInfo Parent Server Address", Type: "hex"},
	113: {Code: 113, Name: "Netinfo Tag", Length: "N", Description: "NetInfo Parent Server Tag", Type: "hex"},
	114: {Code: 114, Name: "DHCP Captive-Portal", Length: "N", Description: "DHCP Captive-Portal", Type: "string"},
	115: {Code: 115, Name: "REMOVED/Unassigned", Length: "", Description: "", Type: "hex"},
	116: {Code: 116, Name: "Auto-Config", Length: "N", Description: "DHCP Auto-Configuration", Type: "uint8"},
	117: {Code: 117, Name: "Name Service Search", Length: "N", Description: "Name Service Search", Type: "string"},
	118: {Code: 118, Name: "Subnet Selection Option", Length: "4", Description: "Subnet Selection Option", Type: "hex"},
	119: {Code: 119, Name: "Domain Search", Length: "N", Description: "DNS domain search list", Type: "hex"},
	120: {Code: 120, Name: "SIP Servers DHCP Option", Length: "N", Description: "SIP Servers DHCP Option", Type: "hex"},
	121: {Code: 121, Name: "Classless Static Route Option", Length: "N", Description: "Classless Static Route Option", Type: "routes"},
	122: {Code: 122, Name: "CCC", Length: "N", Description: "CableLabs Client Configuration", Type: "hex"},
	123: {Code: 123, Name: "GeoConf Option", Length: "16", Description: "GeoConf Option", Type: "hex"},
	124: {Code: 124, Name: "V-I Vendor Class", Length: "", Description: "Vendor-Identifying Vendor Class", Type: "hex"},
	125: {Code: 125, Name: "V-I Vendor-Specific Information", Length: "", Description: "Vendor-Identifying Vendor-Specific Information", Type: "hex"},
	126: {Code: 126, Name: "Removed/Unassigned", Length: "", Description: "", Type: "hex"},
	127: {Code: 127, Name: "Removed/Unassigned", Length: "", Description: "", Type: "hex"},
	128: {Code: 128, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	129: {Code: 129, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	130: {Code: 130, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	131: {Code: 131, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	132: {Code: 132, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	133: {Code: 133, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	134: {Code: 134, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	135: {Code: 135, Name: "PXE - undefined (vendor specific)", Length: "", Description: "", Type: "hex"},
	136: {Code: 136, Name: "OPTION_PANA_AGENT", Length: "", Description: "", Type: "hex"},
	137: {Code: 137, Name: "OPTION_V4_LOST", Length: "", Description: "", Type: "hex"},
	138: {Code: 138, Name: "OPTION_CAPWAP_AC_V4", Length: "N", Description: "CAPWAP Access Controller addresses", Type: "ips"},
	139: {Code: 139, Name: "OPTION-IPv4_Address-MoS", Length: "N", Description: "a series of suboptions", Type: "hex"},
	140: {Code: 140, Name: "OPTION-IPv4_FQDN-MoS", Length: "N", Description: "a series of suboptions", Type: "hex"},
	141: {Code: 141, Name: "SIP UA Configuration Service Domains", Length: "N", Description: "List of domain names to search for SIP User Agent Configuration", Type: "string"},
	142: {Code: 142, Name: "OPTION-IPv4_Address-ANDSF", Length: "N", Description: "ANDSF IPv4 Address Option for DHCPv4", Type: "hex"},
	143: {Code: 143, Name: "OPTION_V4_SZTP_REDIRECT", Length: "N", Description: "This option provides a list of URIs for SZTP bootstrap servers", Type: "ips"},
	144: {Code: 144, Name: "GeoLoc", Length: "16", Description: "Geospatial Location with Uncertainty", Type: "hex"},
	145: {Code: 145, Name: "FORCERENEW_NONCE_CAPABLE", Length: "1", Description: "Forcerenew Nonce Capable", Type: "uint8"},
	146: {Code: 146, Name: "RDNSS Selection", Length: "N", Description: "Information for selecting RDNSS", Type: "hex"},
	147: {Code: 147, Name: "OPTION_V4_DOTS_RI", Length: "N", Description: "The name of the peer DOTS agent.", Type: "string"},
	148: {Code: 148, Name: "OPTION_V4_DOTS_ADDRESS", Length: "N (the minimal length is 4)", Description: "N/4 IPv4 addresses of peer DOTS agent(s).", Type: "hex"},
	149: {Code: 149, Name: "Unassigned", Length: "", Description: "", Type: "hex"},
	150: {Code: 150, Name: "TFTP server address", Length: "", Description: "", Type: "ip"},
	151: {Code: 151, Name: "status-code", Length: "N+1", Description: "Status code and optional N byte text message describing status.", Type: "hex"},
	152: {Code: 152, Name: "base-time", Length: "4", Description: "Absolute time (seconds since Jan 1, 1970) message was sent.", Type: "uint32"},
	153: {Code: 153, Name: "start-time-of-state", Length: "4", Description: "Number of seconds in the past when client entered current state.", Type: "uint32"},
	154: {Code: 154, Name: "query-start-time", Length: "4", Description: "Absolute time (seconds since Jan 1, 1970) for beginning of query.", Type: "uint32"},
	155: {Code: 155, Name: "query-end-time", Length: "4", Description: "Absolute time (seconds since Jan 1, 1970) for end of query.", Type: "uint32"},
	156: {Code: 156, Name: "dhcp-state", Length: "1", Description: "State of IP address.", Type: "uint8"},
	157: {Code: 157, Name: "data-source", Length: "1", Description: "Indicates information came from local or remote server.", Type: "uint8"},
	158: {Code: 158, Name: "OPTION_V4_PCP_SERVER", Length: "Variable; the minimum length is 5.", Description: "Includes one or multiple lists of PCP server IP addresses;        each list is treated as a separate", Type: "hex"},
	159: {Code: 159, Name: "OPTION_V4_PORTPARAMS", Length: "4", Description: "This option is used to configure a set of ports bound to a        shared IPv4 address.", Type: "ip"},
	160: {Code: 160, Name: "Unassigned", Length: "", Description: "Previously assigned by", Type: "hex"},
	161: {Code: 161, Name: "OPTION_MUD_URL_V4", Length: "N (variable)", Description: "Manufacturer Usage Descriptions", Type: "string"},
	162: {Code: 162, Name: "OPTION_V4_DNR", Length: "N", Description: "Encrypted DNS Server", Type: "hex"},
	175: {Code: 175, Name: "Etherboot (Tentatively Assigned - 2005-06-23)", Length: "", Description: "", Type: "hex"},
	176: {Code: 176, Name: "IP Telephone (Tentatively Assigned - 2005-06-23)", Length: "", Description: "", Type: "hex"},
	177: {Code: 177, Name: "Etherboot (Tentatively Assigned - 2005-06-23)", Length: "", Description: "", Type: "hex"},
	208: {Code: 208, Name: "PXELINUX Magic", Length: "4", Description: "magic string = F1:00:74:7E", Type: "hex"},
	209: {Code: 209, Name: "Configuration File", Length: "N", Description: "Configuration file", Type: "string"},
	210: {Code: 210, Name: "Path Prefix", Length: "N", Description: "Path Prefix Option", Type: "string"},
	211: {Code: 211, Name: "Reboot Time", Length: "4", Description: "Reboot Time", Type: "uint32"},
	212: {Code: 212, Name: "OPTION_6RD", Length: "18 + N", Description: "OPTION_6RD with N/4 6rd BR addresses", Type: "hex"},
	213: {Code: 213, Name: "OPTION_V4_ACCESS_DOMAIN", Length: "N", Description: "Access Network Domain Name", Type: "string"},
	220: {Code: 220, Name: "Subnet Allocation Option", Length: "N", Description: "Subnet Allocation Option", Type: "hex"},
	221: {Code: 221, Name: "Virtual Subnet Selection (VSS) Option", Length: "", Description: "", Type: "hex"},
	255: {Code: 255, Name: "End", Length: "0", Description: "None", Type: "none"},
}
